### ISSUE TITLE
Publish Xef Core in npm

### ISSUE THREAD

**Issue by rafaparadela** [xebia-functional/xef#502]
We want to use Xef Core in the TypeScript environment, so we need to make sure we are compiling the core into JS and publishing it in the NPM repository at every release.

A couple of relevant links:

- https://kotlinlang.org/docs/js-ir-compiler.html#minification-of-member-names-in-production
- https://kotlinlang.org/docs/multiplatform-library.html#what-s-next

**Comment by tomascayuelas** [comment]
@rafaparadela Due to the status of the capabilities that JS(IR) gives us in kotlin, based on the testing I have done it is not able to export certain language functionality such as `suspend functions`, `annotation class`, and more class types. 

...more info:
- https://youtrack.jetbrains.com/issue/KT-56281/KJS-Cant-export-suspend-functions
- https://youtrack.jetbrains.com/issue/KT-53000/KJS-IR-document-JsExport-limits
- https://dev.to/touchlab/jsexport-guide-for-exposing-kotlin-to-js-20l9#annotations-vs
